# Generated by Django 4.2.7 on 2024-01-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratice', '0003_alter_question_test_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_name',
            field=models.CharField(default='Quest', max_length=200),
            preserve_default=False,
        ),
    ]
