# Generated by Django 4.2.7 on 2024-01-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratice', '0005_question_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test_cases',
        ),
        migrations.AddField(
            model_name='question',
            name='test_cases',
            field=models.ManyToManyField(blank=True, to='pratice.testcase'),
        ),
    ]
