# Generated by Django 4.2.7 on 2024-01-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratice', '0006_remove_question_test_cases_question_test_cases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test_cases',
        ),
    ]
