# Generated by Django 4.2.7 on 2024-01-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratice', '0007_remove_question_test_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_cases',
            field=models.ManyToManyField(blank=True, to='pratice.testcase'),
        ),
    ]
