# Generated by Django 4.2.7 on 2024-01-19 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pratice', '0008_question_test_cases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test_cases',
        ),
        migrations.AddField(
            model_name='testcase',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='pratice.question'),
        ),
    ]
